### ISSUE TITLE
How to run locally? 

### ISSUE THREAD

**Issue by brdhunga** [do-community/functions-resources#1]
I did not see any function related sub command in doctl.

**Comment by amycodes** [comment]
To use Functions with AppPlatform, refer to the functions segment of the appspec reference: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
To use Functions as standalone, refer to this doctl command: https://docs.digitalocean.com/reference/doctl/reference/sandbox/

Thanks for your interest!
