### ISSUE TITLE
Ruby Example?

### ISSUE THREAD

**Issue by eadz** [do-community/functions-resources#2]
That's a ruby logo there right? Would be great to have a Ruby example. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/11939/170124491-5dcb5d22-9083-4b36-8251-47233e07e835.png">

**Comment by amycodes** [comment]
Hello! Ruby is in the pipeline, however at launch the runtimes available are Go, Python, NodeJS, and PHP. Thank you for your interest!
