### ISSUE TITLE
PHP example

### ISSUE THREAD

**Issue by dbalabka** [do-community/functions-resources#3]
While it is stated that there is PHP support, I can not find an example that shows how a PHP application can be created using DO serverless solutions: https://docs.digitalocean.com/products/functions/quickstart/

Could you please add an example for PHP? It would be highly useful to see Symfony and Laravel examples. 

Thanks in advance

**Comment by dbalabka** [comment]
It seems that repository just missing a link to https://github.com/digitalocean/sample-functions-php-helloworld

**Comment by amycodes** [comment]
Hello! We are still creating new sample apps. Also take a look at this repository to see how to build with composer: https://github.com/digitalocean/sample-functions-php-numberstowords. Thank you for your interest!
